[debug] [2025-03-30T19:18:30.001Z] ----------------------------------------------------------------------
[debug] [2025-03-30T19:18:30.002Z] Command:       /Users/vinithyareddy/.nvm/versions/node/v16.20.2/bin/node /Users/vinithyareddy/.nvm/versions/node/v16.20.2/bin/firebase use --add
[debug] [2025-03-30T19:18:30.002Z] CLI Version:   12.9.1
[debug] [2025-03-30T19:18:30.002Z] Platform:      darwin
[debug] [2025-03-30T19:18:30.002Z] Node Version:  v16.20.2
[debug] [2025-03-30T19:18:30.003Z] Time:          Sun Mar 30 2025 15:18:30 GMT-0400 (Eastern Daylight Time)
[debug] [2025-03-30T19:18:30.003Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-03-30T19:18:30.004Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2025-03-30T19:18:30.038Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-03-30T19:18:30.038Z] > authorizing via signed-in user (podduturivinithya@gmail.com)
[debug] [2025-03-30T19:18:30.038Z] > refreshing access token with scopes: []
[debug] [2025-03-30T19:18:30.039Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2025-03-30T19:18:30.039Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-03-30T19:18:30.171Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[debug] [2025-03-30T19:18:30.171Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2025-03-30T19:18:30.180Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects pageSize=1000
[debug] [2025-03-30T19:18:30.181Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2025-03-30T19:18:30.182Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2025-03-30T19:18:30.587Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects 200
[debug] [2025-03-30T19:18:30.587Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects [omitted]
[debug] [2025-03-30T19:20:03.103Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at MuteStream.ondata (node:internal/streams/legacy:20:31)
    at MuteStream.emit (node:events:513:28)
    at MuteStream.emit (node:domain:489:12)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.106Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.106Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.107Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.108Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.108Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.109Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.109Z] Error: write EIO
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at WriteStream.Socket._writeGeneric (node:net:905:11)
    at WriteStream.Socket._write (node:net:917:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at WriteStream.Writable.write (node:internal/streams/writable:336:10)
    at Console.log (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston/lib/winston/transports/console.js:87:23)
    at Console._write (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/winston-transport/modern.js:103:17)
    at doWrite (/Users/vinithyareddy/.nvm/versions/node/v16.20.2/lib/node_modules/firebase-tools/node_modules/readable-stream/lib/_stream_writable.js:390:139)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-30T19:20:03.110Z] Error: read EIO
    at TTY.onStreamRead (node:internal/stream_base_commons:217:20)
[error] 
[error] Error: An unexpected error has occurred.
